name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-template: 
    uses: TimelessCosmos/action-template/.github/workflows/maven-build.yml@main
    #.<org>/<action-template>/.github/workflows/maven0buil.yml@main   
    # relative path in same repo
    with:
      name: "JIa Yi "
